//! Dependency wiring for derives and runtime construction.
//! `Reads` dependencies declare topics; `Does` dependencies declare effects.
//! The manifest aggregates subscriptions and capabilities from registered types.

use omega_proto::omega::Capability;
use omega_proto::{SystemTopic, Values};

use crate::runtime::context::Context;

/// A field the runtime can build.
pub trait Wiring: Sized + Send + Sync + 'static {
    /// The state topics this field reads and the manifest subscribes to.
    const TOPICS: &'static [SystemTopic] = &[];

    /// Capabilities required by this dependency.
    const CAPABILITIES: &'static [Capability] = &[];

    /// Topics that must be reported before the first render.
    fn required_topics() -> Vec<SystemTopic> {
        Self::TOPICS.to_vec()
    }

    /// Shared stores and access required by this handle.
    fn storage() -> Vec<omega_proto::omega::StorageDescriptor> {
        Vec::new()
    }

    /// Plugin record addresses read by this declaration.
    fn keyspaces() -> Vec<String> {
        Vec::new()
    }

    fn build(context: &Context) -> Self;
}

/// A read-only dependency accepted by render declarations.
#[diagnostic::on_unimplemented(
    message = "a render declaration cannot hold `{Self}`",
    label = "this is not something to read",
    note = "render declarations accept reading handles only",
    note = "if `{Self}` acts, move it to a command, reaction, or the stateful surface’s Effects declaration",
    note = "if it reads, it should be a handle like `Battery`, `Network`, or `Audio`"
)]
pub trait Reads: Wiring {}

/// An effect dependency accepted by commands, reactions, or stateful behavior.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not something a plugin can do",
    label = "not an effect",
    note = "effects are handles like `Notify`, `Session`, `Volume`, or `Shell`"
)]
pub trait Does: Wiring {}

mod effect;
mod reading;
pub(crate) use effect::does;
pub(crate) use reading::reading;

/// Dependency metadata and construction generated by derives.
pub trait Wired: Sized + Send + Sync + 'static {
    /// Every topic its fields read.
    fn topics() -> Vec<SystemTopic>;

    /// Capabilities required by the fields.
    fn capabilities() -> Vec<Capability>;

    fn required_topics() -> Vec<SystemTopic> {
        Self::topics()
    }

    /// Shared stores and access required by the declared fields.
    fn storage() -> Vec<omega_proto::omega::StorageDescriptor> {
        Vec::new()
    }

    /// Plugin record addresses read by this declaration.
    fn keyspaces() -> Vec<String> {
        Vec::new()
    }

    /// Construct one instance with its resolved settings.
    fn build(context: &Context, settings: &Values) -> Self;
}

impl Wired for () {
    fn topics() -> Vec<omega_proto::SystemTopic> {
        Vec::new()
    }
    fn capabilities() -> Vec<omega_proto::omega::Capability> {
        Vec::new()
    }
    fn build(_: &crate::runtime::context::Context, _: &omega_proto::Values) -> Self {}
}
