"""Validate a tagged Omega release and extract its committed release notes."""

import argparse
import json
import os
from pathlib import Path
import re
import subprocess
import tomllib
import urllib.request


class Release:
    def __init__(self, repository: Path, tag: str):
        if not re.fullmatch(r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)", tag):
            raise ValueError("expected a stable version tag such as v0.2.2")
        self.repository = repository
        self.tag = tag
        self.version = tag[1:]
        self.commit = self.git("rev-parse", "--verify", f"refs/tags/{tag}^{{commit}}").strip()
        workspace = tomllib.loads(self.read("Cargo.toml"))["workspace"]
        if workspace["package"]["version"] != self.version:
            raise ValueError("tag does not match the workspace version")
        renderer = json.loads(self.read("crates/omega-renderer/shell/plugins/omega.view/manifest.json"))
        if renderer["version"] != self.version:
            raise ValueError("renderer version does not match the tag")
        self.crates = []
        paths = self.git("ls-tree", "-r", "--name-only", self.commit, "crates").splitlines()
        for path in paths:
            if not re.fullmatch(r"crates/[^/]+/Cargo.toml", path):
                continue
            package = tomllib.loads(self.read(path))["package"]
            version = package["version"]
            if version == {"workspace": True}:
                version = workspace["package"]["version"]
            if version != self.version:
                raise ValueError(f"{package['name']} version does not match the tag")
            if package.get("publish") is not False:
                self.crates.append(package["name"])
        if "omega-cli" not in self.crates or "omega-rs" not in self.crates:
            raise ValueError("release must contain the CLI and SDK crates")
        self.notes = self.extract_notes(self.read("CHANGELOG.md"), self.version)

    def git(self, *args: str) -> str:
        return subprocess.check_output(
            ["git", *args], cwd=self.repository, text=True, stderr=subprocess.PIPE
        )

    def read(self, path: str) -> str:
        return self.git("show", f"{self.commit}:{path}")

    @staticmethod
    def extract_notes(changelog: str, version: str) -> str:
        # cliff.toml owns this heading format; stop at the next release, not a subsection.
        heading = f"## What's Changed in {version}"
        lines = changelog.splitlines()
        starts = [index for index, line in enumerate(lines) if line == heading]
        if len(starts) != 1:
            raise ValueError(f"expected exactly one changelog section for {version}")
        section = []
        for line in lines[starts[0] + 1 :]:
            if line.startswith("## ") or line.startswith("<!-- generated by git-cliff"):
                break
            section.append(line)
        notes = "\n".join(section).strip()
        if not any(line.startswith("* ") for line in section):
            raise ValueError(f"changelog section for {version} has no changes")
        return notes + "\n"

    def check_registry(self) -> None:
        for name in self.crates:
            # All Omega crate names have at least four characters.
            path = f"{name[:2]}/{name[2:4]}/{name}"
            request = urllib.request.Request(
                f"https://index.crates.io/{path}", headers={"User-Agent": "omega-release"}
            )
            with urllib.request.urlopen(request, timeout=30) as response:
                entries = [json.loads(line) for line in response if line.strip()]
            if not any(
                entry["vers"] == self.version and not entry["yanked"] for entry in entries
            ):
                raise ValueError(f"publish {name} {self.version} to crates.io before releasing binaries")

    def write(self, directory: Path) -> None:
        directory.mkdir(parents=True, exist_ok=True)
        (directory / "notes.md").write_text(self.notes)
        metadata = {"tag": self.tag, "version": self.version, "commit": self.commit}
        (directory / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
        if output := os.environ.get("GITHUB_OUTPUT"):
            with open(output, "a") as stream:
                for key, value in metadata.items():
                    stream.write(f"{key}={value}\n")

    @classmethod
    def run(cls) -> None:
        parser = argparse.ArgumentParser(description=__doc__)
        parser.add_argument("tag")
        parser.add_argument("output", type=Path)
        args = parser.parse_args()
        try:
            release = cls(Path.cwd(), args.tag)
            release.check_registry()
            release.write(args.output)
        except (ValueError, KeyError, OSError, subprocess.CalledProcessError) as error:
            parser.exit(1, f"release preparation failed: {error}\n")


if __name__ == "__main__":
    Release.run()
