//! Typed invocations of commands belonging to the drawing plugin.
use crate::{Command, Input};
use omega_proto::omega::{Bind as WireBind, Value};
use std::marker::PhantomData;

/// Identity shared by registration and typed UI bindings. Generated by `Command`.
#[doc(hidden)]
pub trait CommandName {
    const NAME: &'static str;
}

/// A reference to a command, without its effects or runtime instance.
/// `#[derive(Command)]` provides a value with the command's type name.
///
/// ```
/// use omega::{Command, Percent};
/// use omega::ui::Slider;
/// #[derive(omega::Command)]
/// struct SetVolume { volume: omega::audio::Volume }
/// impl Command for SetVolume {
///     type Input = Percent;
///     type Output = ();
///     async fn call(&self, value: Percent) -> omega::Result<()> {
///         self.volume.set(value).await
///     }
/// }
/// Slider::new(Percent::whole(50)).on_change(SetVolume);
/// ```
pub struct CommandRef<C>(PhantomData<fn() -> C>);
impl<C> Copy for CommandRef<C> {}
impl<C> Clone for CommandRef<C> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<C> std::fmt::Debug for CommandRef<C> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CommandRef")
    }
}
impl<C> CommandRef<C> {
    #[doc(hidden)]
    pub const INSTANCE: Self = Self(PhantomData);
}
impl<C: Command> CommandRef<C> {
    /// Bind a complete input for a button to submit.
    pub fn with(self, input: C::Input) -> Bind<()> {
        Bind {
            command: C::NAME.to_string(),
            args: input.encode(),
            input: PhantomData,
        }
    }
}

/// A command invocation expecting an interaction of type `I`.
/// Controls accept only bindings matching the value they submit.
///
/// A boolean control cannot invoke a command expecting a percentage:
///
/// ```compile_fail
/// use omega::{Command, Percent, ui::Toggle};
/// #[derive(omega::Command)]
/// struct SetVolume {}
/// impl Command for SetVolume {
///     type Input = Percent;
///     type Output = ();
///     async fn call(&self, _: Percent) -> omega::Result<()> { Ok(()) }
/// }
/// Toggle::new(false).on_change(SetVolume);
/// ```
///
/// A button must bind the input a command requires:
///
/// ```compile_fail
/// use omega::{Command, ui::Button};
/// #[derive(omega::Command)]
/// struct Join {}
/// impl Command for Join {
///     type Input = String;
///     type Output = ();
///     async fn call(&self, _: String) -> omega::Result<()> { Ok(()) }
/// }
/// Button::new("Join").on_press(Join);
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct Bind<I> {
    command: String,
    args: Vec<Value>,
    input: PhantomData<fn(I)>,
}
impl<C: Command> From<CommandRef<C>> for Bind<C::Input> {
    fn from(_: CommandRef<C>) -> Self {
        Self {
            command: C::NAME.to_string(),
            args: Vec::new(),
            input: PhantomData,
        }
    }
}
impl<I> Bind<I> {
    pub(crate) fn into_wire(self) -> WireBind {
        WireBind {
            command: self.command,
            args: self.args,
        }
    }
}
