//! Typed command identity and fully bound invocations.
use crate::{Command, Input, ui::Bind};
use std::marker::PhantomData;

/// Identity shared by registration and typed UI bindings. Generated by `Command`.
#[doc(hidden)]
pub trait CommandName {
    const NAME: &'static str;
}

/// A reference to a command, without its effects or runtime instance.
/// `#[derive(Command)]` provides a value with the command's type name.
///
/// ```
/// use omega::{Command, Percent};
/// use omega::ui::Slider;
/// #[derive(omega::Command)]
/// struct SetVolume { volume: omega::platform::audio::Volume }
/// impl Command for SetVolume {
///     type Input = Percent;
///     type Output = ();
///     async fn call(&self, value: Percent) -> omega::Result<()> {
///         self.volume.set(value).await
///     }
/// }
/// Slider::new(Percent::whole(50)).on_change(SetVolume);
/// ```
pub struct CommandRef<C>(PhantomData<fn() -> C>);
impl<C> Copy for CommandRef<C> {}
impl<C> Clone for CommandRef<C> {
    fn clone(&self) -> Self {
        *self
    }
}
impl<C> std::fmt::Debug for CommandRef<C> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CommandRef")
    }
}
impl<C> CommandRef<C> {
    #[doc(hidden)]
    pub const INSTANCE: Self = Self(PhantomData);
}
impl<C: Command> CommandRef<C> {
    /// Bind a complete input for a button to submit.
    pub fn with(self, input: C::Input) -> Bind<()> {
        Bind::command(C::NAME, input.encode())
    }
}
