use omega_keyboard::{Chord, Key, KeyEvent, Modifiers, Phase};

struct Cases;
impl Cases {
    fn source() -> String {
        use Key::*;
        let keys = [
            Escape,
            Enter,
            Tab,
            Backspace,
            Delete,
            Insert,
            Home,
            End,
            PageUp,
            PageDown,
            ArrowLeft,
            ArrowRight,
            ArrowUp,
            ArrowDown,
            Space,
            F1,
            F2,
            F3,
            F4,
            F5,
            F6,
            F7,
            F8,
            F9,
            F10,
            F11,
            F12,
            Character('a'),
            Character('K'),
            Character('é'),
            Character('İ'),
            Character(' '),
            Character('😀'),
        ];
        let mut source = String::from(
            "// Generated by tests/keyboard.rs.\n.pragma library\nfunction identities() { return [\n",
        );
        for key in keys {
            source.push_str(&format!(
                "{{qt:{},identity:{:?}}},\n",
                Self::qt(key),
                key.identity()
            ));
        }
        source.push_str("] }\nfunction cases() { return [\n");
        for key in [Character('K'), Enter] {
            for modifiers in [
                Modifiers::NONE,
                Modifiers::CONTROL,
                Modifiers::CONTROL | Modifiers::SHIFT,
                Modifiers::ALT_GRAPH,
            ] {
                for phase in [Phase::Press, Phase::Release] {
                    for repeat in [false, true] {
                        let event = KeyEvent {
                            key,
                            modifiers,
                            phase,
                            repeat,
                        };
                        for chord in [
                            Chord::new(key).ctrl(),
                            Chord::new(key)
                                .with(Modifiers::ALT_GRAPH)
                                .on_release()
                                .repeat(),
                        ] {
                            source.push_str(&format!("{{qt:{},identity:{:?},modifiers:{},release:{},repeat:{},binding:{{key:{:?},modifiers:{},release:{},repeat:{}}},matches:{}}},\n",
                                Self::qt(key), key.identity(), modifiers.bits(), phase == Phase::Release, repeat,
                                chord.key().identity(), chord.modifiers().bits(), chord.phase() == Phase::Release, chord.allows_repeat(), chord.matches(&event)));
                        }
                    }
                }
            }
        }
        source.push_str("] }\n");
        source
    }
    fn qt(key: Key) -> u32 {
        use Key::*;
        match key {
            Character(c) => c as u32,
            Space => 32,
            Escape => 0x1000000,
            Tab => 0x1000001,
            Backspace => 0x1000003,
            Enter => 0x1000004,
            Insert => 0x1000006,
            Delete => 0x1000007,
            Home => 0x1000010,
            End => 0x1000011,
            ArrowLeft => 0x1000012,
            ArrowUp => 0x1000013,
            ArrowRight => 0x1000014,
            ArrowDown => 0x1000015,
            PageUp => 0x1000016,
            PageDown => 0x1000017,
            F1 => 0x1000030,
            F2 => 0x1000031,
            F3 => 0x1000032,
            F4 => 0x1000033,
            F5 => 0x1000034,
            F6 => 0x1000035,
            F7 => 0x1000036,
            F8 => 0x1000037,
            F9 => 0x1000038,
            F10 => 0x1000039,
            F11 => 0x100003a,
            F12 => 0x100003b,
        }
    }
}

#[test]
fn renderer_matching_corpus_is_current() {
    let path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("shell/tests/KeyboardCases.js");
    let source = Cases::source();
    if std::env::var_os("OMEGA_REGENERATE").is_some() {
        std::fs::write(&path, &source).unwrap();
    }
    assert_eq!(
        std::fs::read_to_string(path).unwrap(),
        source,
        "run OMEGA_REGENERATE=1 cargo test -p omega-renderer --test keyboard"
    );
}
